server:
  port: '5000'

---
spring:
  profiles.active: "prod"
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mydb
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: '"Welcome to the dev environment baby"'
---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mydbprod
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: '"Welcome to the prod enviroment, baby"'

management:
  endpoints:
    web:
      exposure:
        include: "*"







